// Builds sea/<platform>/rts-bin — the prebuilt single-executable RTS binary
// deployed by SshPipeClient's 'binary' deploy flavor, so a remote needs
// NOTHING installed (no node on the remote PATH). The binary is the official
// node dist with dist/rts.cjs injected as a Node SEA blob.
//
// Pipeline:
//   1. dist/rts.cjs (the `build` script's CommonJS artifact — SEA requires a
//      CJS main) is wrapped into a SEA blob via `node --experimental-sea-config`.
//   2. The pinned carrier node (v24.15.0, matching .nvmrc/engines) is
//      downloaded from nodejs.org with SHASUMS256 verification and cached
//      under sea/.cache/; NODE_DIST_BASE_URL overrides the mirror base.
//   3. Its bin/node is extracted with the system tar (present on Git Bash /
//      macOS / Linux) and postject injects the blob with the same sentinel
//      fuse apps/kimi-code's native pipeline uses.
//
// A SEA blob is only loadable by the EXACT node version that generated it —
// a blob from another major is silently ignored at runtime (verified
// empirically: a node-25 blob fused into a node-24 binary exits 0 without
// running). The blob is therefore generated with process.execPath when it IS
// v24.15.0, and otherwise with a downloaded pinned host-platform node.
//
// postject is resolved WITHOUT adding a dependency to this package (a new
// devDep would change pnpm-lock.yaml and break flake.nix's pinned
// fetchPnpmDeps hash): KIMI_POSTJECT_PATH →
// <repo>/apps/kimi-code/node_modules/.bin/postject[.cmd] (already in the
// lockfile via the CLI) → an error telling you to run from the monorepo.
//
// Usage: node scripts/build-sea.mjs [--platform=<key>] with a key of
// linux-x64 | linux-arm64 | darwin-x64 | darwin-arm64 (default: both linux
// keys). Artifacts under sea/ are large, built on demand, and gitignored.
//
// Known limitations: official node dists require glibc >= 2.28 on Linux (no
// musl/Alpine remotes); darwin artifacts need code-signing on a Mac and are
// out of scope for now — POSIX server remotes first.

import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { chmod, mkdir, mkdtemp, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { basename, dirname, join, resolve } from 'node:path';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

const packageRoot = resolve(import.meta.dirname, '..');
const repoRoot = resolve(packageRoot, '..', '..');
const seaRoot = join(packageRoot, 'sea');
const cacheDir = join(seaRoot, '.cache');
const seaConfigPath = join(seaRoot, 'sea-config.json');
const blobPath = join(seaRoot, 'rts-sea.blob');
const rtsCjsPath = join(packageRoot, 'dist', 'rts.cjs');

/** The carrier node the binary is cut from; the blob must be generated by this exact version. */
const CARRIER_NODE_VERSION = '24.15.0';
/** Same sentinel fuse as apps/kimi-code's native pipeline (scripts/native/paths.mjs). */
const SENTINEL_FUSE = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2';
const TARGET_PLATFORM_KEYS = ['linux-x64', 'linux-arm64', 'darwin-x64', 'darwin-arm64'];
const DEFAULT_PLATFORMS = ['linux-x64', 'linux-arm64'];

const baseUrl = (process.env.NODE_DIST_BASE_URL ?? 'https://nodejs.org/dist').replace(/\/+$/, '');

async function exists(path) {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

async function sha256File(path) {
  const hash = createHash('sha256');
  for await (const chunk of createReadStream(path)) {
    hash.update(chunk);
  }
  return hash.digest('hex');
}

async function downloadFile(url, dest) {
  const response = await fetch(url);
  if (!response.ok || response.body === null) {
    throw new Error(`download failed (HTTP ${response.status}): ${url}`);
  }
  await mkdir(dirname(dest), { recursive: true });
  await pipeline(Readable.fromWeb(response.body), createWriteStream(dest));
}

// ── pinned node download (verified + cached) ──────────────────────────

function archiveName(key) {
  return `node-v${CARRIER_NODE_VERSION}-${key}.${key.startsWith('win') ? 'zip' : 'tar.gz'}`;
}

async function publishedSha256(name) {
  const shasumsPath = join(cacheDir, `SHASUMS256-v${CARRIER_NODE_VERSION}.txt`);
  if (!(await exists(shasumsPath))) {
    await downloadFile(`${baseUrl}/v${CARRIER_NODE_VERSION}/SHASUMS256.txt`, shasumsPath);
  }
  for (const line of (await readFile(shasumsPath, 'utf8')).split('\n')) {
    const [sha, file] = line.trim().split(/\s+/);
    if (file === name) return sha;
  }
  throw new Error(`no SHA-256 published for ${name}`);
}

async function downloadNodeArchive(key) {
  const name = archiveName(key);
  const dest = join(cacheDir, name);
  const expected = await publishedSha256(name);
  if ((await exists(dest)) && (await sha256File(dest)) === expected) {
    return dest;
  }
  console.log(`[build-sea] downloading ${name}`);
  await downloadFile(`${baseUrl}/v${CARRIER_NODE_VERSION}/${name}`, dest);
  const actual = await sha256File(dest);
  if (actual !== expected) {
    await rm(dest, { force: true });
    throw new Error(`SHA-256 mismatch for ${name}: expected ${expected}, got ${actual}`);
  }
  return dest;
}

/** Extract the node binary from a dist archive into `destDir` as `destName`. */
async function extractNodeBinary(archive, key, destDir, destName) {
  const isWin = key.startsWith('win');
  const member = `node-v${CARRIER_NODE_VERSION}-${key}/${isWin ? 'node.exe' : 'bin/node'}`;
  const tmp = await mkdtemp(join(cacheDir, 'extract-'));
  try {
    if (isWin) {
      await run('unzip', ['-j', '-o', archive, member, '-d', tmp]);
    } else {
      // Relative to the cache dir: GNU tar on Windows mistakes a drive-letter
      // path for an rmt remote spec (`C:` host) and fails to "connect".
      await run(
        'tar',
        ['-xzf', basename(archive), '-C', basename(tmp), '--strip-components=2', member],
        { cwd: cacheDir },
      );
    }
    await mkdir(destDir, { recursive: true });
    await rename(join(tmp, isWin ? 'node.exe' : 'node'), join(destDir, destName));
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}

// ── SEA blob ───────────────────────────────────────────────────────────

function hostPlatformKey() {
  const os = { linux: 'linux', darwin: 'darwin', win32: 'win' }[process.platform];
  const arch = { x64: 'x64', arm64: 'arm64' }[process.arch];
  if (os === undefined || arch === undefined) {
    throw new Error(
      `no pinned node dist for host ${process.platform}/${process.arch}; ` +
        `run with node v${CARRIER_NODE_VERSION} instead`,
    );
  }
  return `${os}-${arch}`;
}

/** The node that generates the blob: the local one iff it IS the pinned version. */
async function ensureBlobNode() {
  if (process.version === `v${CARRIER_NODE_VERSION}`) {
    return process.execPath;
  }
  console.log(
    `[build-sea] local node is ${process.version}; the SEA blob must come from exactly ` +
      `v${CARRIER_NODE_VERSION} — using a downloaded pinned host node`,
  );
  const key = hostPlatformKey();
  const archive = await downloadNodeArchive(key);
  const binName = key.startsWith('win') ? 'node.exe' : 'node';
  const dir = join(cacheDir, 'host', key);
  if (!(await exists(join(dir, binName)))) {
    await extractNodeBinary(archive, key, dir, binName);
    if (!key.startsWith('win')) {
      await chmod(join(dir, binName), 0o755);
    }
  }
  return join(dir, binName);
}

async function writeSeaConfig() {
  const config = {
    // Paths resolve against the cwd (packageRoot) of the generation run.
    main: 'dist/rts.cjs',
    output: 'sea/rts-sea.blob',
    disableExperimentalSEAWarning: true,
    useCodeCache: false,
    useSnapshot: false,
  };
  await writeFile(seaConfigPath, `${JSON.stringify(config, null, 2)}\n`);
}

// ── postject ───────────────────────────────────────────────────────────

async function resolvePostject() {
  const fromEnv = process.env.KIMI_POSTJECT_PATH;
  if (fromEnv !== undefined && fromEnv !== '') {
    return fromEnv;
  }
  const bin = join(
    repoRoot,
    'apps',
    'kimi-code',
    'node_modules',
    '.bin',
    process.platform === 'win32' ? 'postject.CMD' : 'postject',
  );
  if (await exists(bin)) {
    return bin;
  }
  throw new Error(
    `postject not found at ${bin}. Run from the kimi-code monorepo (postject rides ` +
      'apps/kimi-code\'s devDependency) or point KIMI_POSTJECT_PATH at a postject binary.',
  );
}

// ── per-platform carrier ───────────────────────────────────────────────

async function buildCarrier(key, postject) {
  const archive = await downloadNodeArchive(key);
  const outDir = join(seaRoot, key);
  const out = join(outDir, 'rts-bin');
  await extractNodeBinary(archive, key, outDir, 'rts-bin');
  await chmod(out, 0o755);
  const args = [out, 'NODE_SEA_BLOB', blobPath, '--sentinel-fuse', SENTINEL_FUSE];
  if (key.startsWith('darwin')) {
    args.push('--macho-segment-name', 'NODE_SEA');
  }
  await run(postject, args);
  const info = await stat(out);
  console.log(
    `[build-sea] ${key}: ${out} (${(info.size / 1024 / 1024).toFixed(1)} MB, ` +
      `sha256 ${await sha256File(out)})`,
  );
}

// ── exec helper (.cmd shims need cmd.exe on Windows) ───────────────────

function commandForExecFile(command, args) {
  if (process.platform !== 'win32' || !/\.(?:bat|cmd)$/i.test(command)) {
    return { command, args };
  }
  const shellCommand = [command, ...args]
    .map(arg => `"${String(arg).replaceAll('"', '""')}"`)
    .join(' ');
  return {
    command: process.env.ComSpec ?? 'cmd.exe',
    args: ['/d', '/s', '/c', `"${shellCommand}"`],
    options: { windowsVerbatimArguments: true },
  };
}

async function run(command, args, options = {}) {
  const exec = commandForExecFile(command, args);
  try {
    const { stdout, stderr } = await execFileAsync(exec.command, exec.args, {
      cwd: packageRoot,
      maxBuffer: 64 * 1024 * 1024,
      ...exec.options,
      ...options,
    });
    if (stdout.trim()) console.log(stdout.trim());
    if (stderr.trim()) console.error(stderr.trim());
  } catch (error) {
    const details = [error.stdout?.trim(), error.stderr?.trim(), error.message]
      .filter(Boolean)
      .join('\n');
    throw new Error(`command failed: ${basename(command)} ${args.join(' ')}\n${details}`);
  }
}

// ── main ───────────────────────────────────────────────────────────────

async function main() {
  const platformArg = process.argv.find(arg => arg.startsWith('--platform='));
  const platforms =
    platformArg === undefined ? DEFAULT_PLATFORMS : [platformArg.slice('--platform='.length)];
  for (const key of platforms) {
    if (!TARGET_PLATFORM_KEYS.includes(key)) {
      throw new Error(`unknown --platform=${key} (expected one of ${TARGET_PLATFORM_KEYS.join(', ')})`);
    }
  }

  if (!(await exists(rtsCjsPath))) {
    throw new Error(
      `dist/rts.cjs not found — run \`pnpm --filter @moonshot-ai/remote-ssh build\` first ` +
        '(or use the `build:sea` script, which does).',
    );
  }
  await mkdir(cacheDir, { recursive: true });
  await writeSeaConfig();
  const blobNode = await ensureBlobNode();
  await run(blobNode, ['--experimental-sea-config', seaConfigPath]);
  if (!(await exists(blobPath))) {
    throw new Error(`SEA blob was not produced at ${blobPath}`);
  }
  const postject = await resolvePostject();
  for (const key of platforms) {
    await buildCarrier(key, postject);
  }
}

main().catch(error => {
  console.error(`[build-sea] ${error.message}`);
  process.exit(1);
});
