/**
 * Regenerates `src/stateful-shell/shellStateFilter.generated.ts` by probing
 * an isolated bash for its bookkeeping variables (see
 * `src/stateful-shell/filterDetection.ts`). Run:
 *
 *   pnpm --filter @moonshot-ai/kaos gen:shell-state-filter
 *
 * The drift check `test/shell-state-filter.test.ts` fails when the committed
 * artifact no longer matches the live bash — that is the cue to re-run this.
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { detectEnvironmentFromNode } from '../src/environment';
import {
  detectShellStateFilter,
  type ShellStateFilterDetection,
} from '../src/stateful-shell/filterDetection';

const here = import.meta.dirname;
const target = join(here, '../src/stateful-shell/shellStateFilter.generated.ts');

function wrapNames(label: string, names: readonly string[]): string[] {
  const lines: string[] = [];
  let current = `//   ${label} (${names.length}): `;
  for (const name of names) {
    if (current.length + name.length + 2 > 78) {
      lines.push(current);
      current = `//     ${name}`;
    } else {
      current += (current.endsWith(': ') ? '' : ', ') + name;
    }
  }
  lines.push(current);
  return lines;
}

function render(d: ShellStateFilterDetection): string {
  // Chunk the alternation so the generated file stays formatter-friendly.
  // Every continued chunk keeps its trailing '|' — the separator must
  // survive the string concatenation.
  const chunks: string[] = [];
  let chunk = '';
  for (const name of d.all) {
    if (chunk.length + name.length + 1 > 72) {
      chunks.push(`${chunk}|`);
      chunk = '';
    }
    chunk += (chunk === '' ? '' : '|') + name;
  }
  if (chunk !== '') chunks.push(chunk);

  return [
    '// GENERATED by scripts/gen-shell-state-filter.mts — do not edit by hand.',
    '// Regenerate: pnpm --filter @moonshot-ai/kaos gen:shell-state-filter',
    `// Detected ${new Date().toISOString().slice(0, 10)} against bash ${d.bashVersion} (${process.platform}).`,
    ...wrapNames('readonly', d.readonlyNames),
    ...wrapNames('volatile', d.volatileNames),
    ...wrapNames('lazy    ', d.lazyNames),
    '',
    '/**',
    ' * Alternation body of the exclusion regex for bash bookkeeping variables,',
    ' * used by the stateful-shell protocol (`__KIMI_KEEPVARS_RE` in',
    ' * `./resuming.ts`), which anchors it and appends the protocol prefixes.',
    ' */',
    'export const SHELL_STATE_BOOKKEEPING_ALTS =',
    chunks.map((c, i) => `  '${c}'${i < chunks.length - 1 ? ' +' : ';'}`).join('\n'),
    '',
  ].join('\n');
}

const env = await detectEnvironmentFromNode();
const detection = await detectShellStateFilter(env.shellPath);
await writeFile(target, render(detection));
console.log(
  `wrote ${target}: ${detection.all.length} bookkeeping variables ` +
    `(readonly ${detection.readonlyNames.length}, volatile ${detection.volatileNames.length}, ` +
    `lazy ${detection.lazyNames.length}) from bash ${detection.bashVersion}`,
);
