// GENERATED by scripts/gen-shell-state-filter.mts — do not edit by hand.
// Regenerate: pnpm --filter @moonshot-ai/kaos gen:shell-state-filter
// Detected 2026-08-03 against bash 5.2.37(1)-release (win32).
//   readonly (6): BASHOPTS, BASH_VERSINFO, EUID, PPID, SHELLOPTS, UID
//   volatile (23): BASHPID, BASH_ALIASES, BASH_ARGC, BASH_ARGV, BASH_ARGV0
//     BASH_CMDS, BASH_COMMAND, BASH_LINENO, BASH_SOURCE, BASH_SUBSHELL
//     COMP_WORDBREAKS, DIRSTACK, EPOCHREALTIME, EPOCHSECONDS, FUNCNAME
//     GROUPS, HISTCMD, LINENO, PIPESTATUS, RANDOM, SECONDS, SRANDOM, _
//   lazy     (2): BASH_REMATCH, REPLY

/**
 * Alternation body of the exclusion regex for bash bookkeeping variables,
 * used by the stateful-shell protocol (`__KIMI_KEEPVARS_RE` in
 * `./resuming.ts`), which anchors it and appends the protocol prefixes.
 */
export const SHELL_STATE_BOOKKEEPING_ALTS =
  'BASHOPTS|BASHPID|BASH_ALIASES|BASH_ARGC|BASH_ARGV|BASH_ARGV0|BASH_CMDS|' +
  'BASH_COMMAND|BASH_LINENO|BASH_REMATCH|BASH_SOURCE|BASH_SUBSHELL|' +
  'BASH_VERSINFO|COMP_WORDBREAKS|DIRSTACK|EPOCHREALTIME|EPOCHSECONDS|EUID|' +
  'FUNCNAME|GROUPS|HISTCMD|LINENO|PIPESTATUS|PPID|RANDOM|REPLY|SECONDS|' +
  'SHELLOPTS|SRANDOM|UID|_';
